#  Hexo Configuration
## Docs:   https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site

title: ziheng's Blog
subtitle: zihengCat is here!
author: zihengCat
language: zh-CN
timezone: Asia/Shanghai

# URL

## If your site is put in a subdirectory,
## set url as 'http://yoursite.com/child' and root as '/child/'

url: https://zihengcat.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Custom Setting Start

## Site settings

SEOTitle:    zihengCat
header-img:  img/home-bg-d.png
email:       zihenglv@gmail.com
description: ziheng's Blog
keyword:     blog
GoogleSiteVerfication: k8kEwQr5uL4wgMXhsZcUzGeY-tvr8yd23gMfzGcxqrE

## SNS settings

github_username: zihengcat

## Build settings

# if you want to customize anchor.
# check out line:181 of `post.html`
anchorjs: true

## Custom Build settings

### Gitment settings
gitment: true

### Busuanzi.js settings
busuanzijs: true

### Highlight.js settings
highlightjs: true

### MathJax.js settings
mathjaxjs: true

## Sidebar settings

# whether or not using Sidebar.
sidebar: true
sidebar-about-description: "Hi, this is zihengCat, a student live in Hangzhou, China. Learning coding now, SDE I."

# use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-avatar: img/avatar.png

## Featured Tags

# whether or not using Feature-Tags
featured-tags: true

# A tag will be featured if the size of it is more than this condition value
featured-condition-size: 30

## Friends

friends:
  [
#    {
#        title: "Example Friends",
#        href: "#"
#    },
#    {
#        title: "It helps SEO",
#        href: "#"
#    }
  ]


# Custom Setting End

# Directory

source_dir:     source
public_dir:     public
tag_dir:        tags
archive_dir:    i_dont_wanna_use_default_archives
category_dir:   categories
code_dir:       downloads/code
i18n_dir:       lang
skip_render:

# Writing

new_post_name: :title.md    # File name of new posts
default_layout: post
titlecase:      false       # Transform title into titlecase
external_link:  true        # Open external links in new tab
filename_case:  0
render_drafts:  false
post_asset_folder: true
relative_link:  false
future:         true

highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: false

marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true

# Category & Tag

default_category: uncategorized
category_map:
tag_map:

# Date / Time format

## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination

## Set per_page to 0 to disable pagination

per_page: 10
pagination_dir: page

#  Extensions
## Plugins: https://hexo.io/plugins/
## Themes:  https://hexo.io/themes/

theme: zihengblog

#  Deployment
## Docs: https://hexo.io/docs/deployment.html

deploy:
  type: git
  repo: https://github.com/zihengcat/zihengcat.github.io
  branch: master

# EOF

